// <auto-generated />
// Source: Assets/Data/CSV/LocalizeData.csv. Do not edit; retain existing IDs and names.
public enum LocalizeKey
{
    UI_Confirm = 1001,
    NPC_Thought_Hungry = 1002,
    Tutorial_Welcome = 1003,
}
