using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

/// <summary>Pure source generation; reads the last generated source, not a potentially stale assembly.</summary>
public static class LocalizeKeySource
{
    private const string Preamble = "// <auto-generated />\n" +
        "// Source: Assets/Data/CSV/LocalizeData.csv. Do not edit; retain existing IDs and names.\n" +
        "public enum LocalizeKey\n{\n";

    public static bool TryGenerate(string csv, string previousSource, out string source, out string error)
    {
        source = string.Empty;
        if (!LocalizeCsvParser.TryParse(csv, out LocalizeCsvParser.Table table, out error))
            return false;
        if (previousSource != null)
        {
            if (!TryReadPrevious(previousSource, out Dictionary<string, int> previous, out error))
                return false;
            var current = new Dictionary<string, int>(StringComparer.Ordinal);
            foreach (LocalizeCsvParser.Row row in table.Rows)
                current.Add(row.Key, row.Id);
            foreach (KeyValuePair<string, int> member in previous)
            {
                if (!current.TryGetValue(member.Key, out int id))
                {
                    error = "Localize CSV: existing key '" + member.Key + "' (Id " + member.Value +
                        ") was removed or renamed. Restore its row.";
                    return false;
                }
                if (id != member.Value)
                {
                    LocalizeCsvParser.Row changed = null;
                    foreach (LocalizeCsvParser.Row row in table.Rows)
                        if (row.Key == member.Key) changed = row;
                    error = "Localize CSV line " + changed.Line + ": Id for '" + member.Key +
                        "' changed from " + member.Value + " to " + id + ".";
                    return false;
                }
            }
        }
        var sorted = new List<LocalizeCsvParser.Row>(table.Rows);
        sorted.Sort((left, right) => left.Id.CompareTo(right.Id));
        var builder = new StringBuilder(Preamble);
        foreach (LocalizeCsvParser.Row row in sorted)
            builder.Append("    ").Append(row.Key).Append(" = ")
                .Append(row.Id.ToString(CultureInfo.InvariantCulture)).Append(",\n");
        source = builder.Append("}\n").ToString();
        return true;
    }

    private static bool TryReadPrevious(string source, out Dictionary<string, int> members, out string error)
    {
        members = new Dictionary<string, int>(StringComparer.Ordinal);
        error = "LocalizeKey.cs is not an intact generated file. Restore it before regeneration.";
        string normalized = source.TrimStart('\uFEFF').Replace("\r\n", "\n");
        if (!normalized.StartsWith(Preamble, StringComparison.Ordinal) || !normalized.EndsWith("}\n", StringComparison.Ordinal))
            return false;
        string body = normalized.Substring(Preamble.Length, normalized.Length - Preamble.Length - 2);
        var ids = new HashSet<int>();
        foreach (string line in body.Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries))
        {
            Match match = Regex.Match(line, @"^    (\S+) = ([0-9]+),$");
            if (!match.Success || !LocalizeCsvParser.IsValidKey(match.Groups[1].Value) ||
                !int.TryParse(match.Groups[2].Value, NumberStyles.None, CultureInfo.InvariantCulture, out int id) ||
                id <= 0 || !ids.Add(id) || members.ContainsKey(match.Groups[1].Value))
                return false;
            members.Add(match.Groups[1].Value, id);
        }
        if (members.Count == 0)
            return false;
        error = string.Empty;
        return true;
    }
}
